const devices = [
	{
		"fullName": "Apple iPhone 12",
		"manufacturer": "Apple",
		"releasYear": "2020",
		"diagonal": "6,1",
		"manufactureCountry": "Китай",
		"memory": "128",
		"screenFrequancy": "60",
		"nfc": false,
		"esim": true,
		"wirlessCharge": true,
		"cost": "81 990",
		"uid": "RgOHiT",
		"image": "https://drive.google.com/uc?id=17qVjWkGSg_B7PqpXIKVLYjI7ksShGnle"
	},
	{
		"fullName": "Xiaomi Mi 11 Lite",
		"manufacturer": "Xiaomi",
		"releasYear": "2021",
		"diagonal": "6,55",
		"manufactureCountry": "Китай",
		"memory": "128",
		"screenFrequancy": "90",
		"nfc": true,
		"esim": true,
		"wirlessCharge": false,
		"cost": "27 490",
		"uid": "iFznle",
		"image": "https://drive.google.com/uc?id=1vYaKmFJJ0G308QTjBziixpw_G55c3PeL"
	},
	{
		"fullName": "Samsung Galaxy A72",
		"manufacturer": "Samsung",
		"releasYear": "2021",
		"diagonal": "6,7",
		"manufactureCountry": "Вьетнам",
		"memory": "128",
		"screenFrequancy": "90",
		"nfc": true,
		"esim": false,
		"wirlessCharge": true,
		"cost": "32 890",
		"uid": "DSInXL",
		"image": "https://drive.google.com/uc?id=1lb_4w5zKpl5NU8D4Mbr8yy3XMrW67lLY"
	},
	{
		"fullName": "Samsung Galaxy S21",
		"manufacturer": "Samsung",
		"releasYear": "2021",
		"diagonal": "6,2",
		"manufactureCountry": "Вьетнам",
		"memory": "256",
		"screenFrequancy": "120",
		"nfc": true,
		"esim": false,
		"wirlessCharge": true,
		"cost": "79 990",
		"uid": "GBPWgw",
		"image": "https://drive.google.com/uc?id=1Gi3xs7624HMngjyN5tTFOvAF9NFUc6kk"
	},
	{
		"fullName": "Apple iPhone Xr",
		"manufacturer": "Apple",
		"releasYear": "2020",
		"diagonal": "6,1",
		"manufactureCountry": "Китай",
		"memory": "64",
		"screenFrequancy": "60",
		"nfc": true,
		"esim": true,
		"wirlessCharge": false,
		"cost": "35 990",
		"uid": "diSYdU",
		"image": "https://drive.google.com/uc?id=1CO08hHU2nxbM6uQ5s7TsSw_fVd5RuQM5"
	},
	{
		"fullName": "Realme 8 Pro",
		"manufacturer": "Realme",
		"releasYear": "2021",
		"diagonal": "6,4",
		"manufactureCountry": "Китай",
		"memory": "128",
		"screenFrequancy": "60",
		"nfc": true,
		"esim": false,
		"wirlessCharge": false,
		"cost": "21 990",
		"uid": "WuEkcu",
		"image": "https://drive.google.com/uc?id=1exGx4lYwQ8ZGzh4aTp0Ukcsw11HXp-1P"
	}
]

export default devices